foss/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django_comments.feeds import LatestCommentFeed

from visitorsite.views import SignUp


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path("accounts/signup/", SignUp.as_view(template_name="accounts/user_sign_up.html"), name="user_sign_up"),
    path('comments/', include('comments.urls')),
    path('feeds/latest/', LatestCommentFeed()),
    path('', include('visitorsite.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitorsite/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from django.views.generic import TemplateView
from .views import * # noqa


app_name="visitorsite"
urlpatterns = [

    path('', PostListing.as_view(template_name="posts/posts.html"), name="posts_listing_url"),

    path('t/', TopicListing.as_view(template_name="indexes/indexes.html"), name="indexes_url"),

    path('<get_parent_slug>/videos/', VideoPostListing.as_view(template_name="indexes/specific_posts.html"), name="specific_videos_posts_listing_url"),
    path('<get_parent_slug>/news/', NewsPostListing.as_view(template_name="indexes/specific_posts.html"), name="specific_news_posts_listing_url"),
    path('<get_parent_slug>/images/', ImagePostListing.as_view(template_name="indexes/specific_posts.html"), name="specific_images_posts_listing_url"),

    path('videos/', VideoPostListing.as_view(template_name="posts/posts.html"), name="public_videos_posts_listing_url"),
    path('news/', NewsPostListing.as_view(template_name="posts/posts.html"), name="public_news_posts_listing_url"),
    path('images/', ImagePostListing.as_view(template_name="posts/posts.html"), name="public_images_posts_listing_url"),

    path('create/', login_required(PostCreating.as_view(template_name="objects/create_or_update.html")), name="post_creating_url"),
    path('<slug>/update/', login_required(PostUpdating.as_view(template_name="objects/create_or_update.html")), name="post_updating_url"),
    path('<slug>/delete/', login_required(PostDeleting.as_view(template_name="objects/delete.html")), name="post_deleting_url"),
    path('<slug>/image/', PostDetailsViewing.as_view(template_name="posts/image.html"), name="image_viewing_url"),
    path('<slug>/', PostDetailsViewing.as_view(template_name='posts/post_details.html'), name="post_viewing_url"),

    path('embeds/', EmbedListing.as_view(template_name="embeds/embeds.html"), name="embeds_listing_url"),

    path('embeds/create/', login_required(EmbedCreating.as_view(template_name="objects/create_or_update.html")), name="embed_creating_url"),
    path('embeds/<slug>/update/', login_required(EmbedUpdating.as_view(template_name="objects/create_or_update.html")), name="embed_updating_url"),
    path('embeds/<slug>/delete/', login_required(EmbedDeleting.as_view(template_name="objects/delete.html")), name="embed_deleting_url"),
    path('embeds/<slug>/', EmbedDetailsViewing.as_view(template_name='embeds/embed_details.html'), name="embed_viewing_url"),

    path('t/<get_topic_listing_slug>/', SpecificTopicPostsListing.as_view(template_name="indexes/specific_posts.html"), name="index_details_viewing_url"),
]

visitorsite/models/commenting.py
from django.db import models

visitorsite/models/embeds.py
from django.db import models
from django.template.defaultfilters import truncatechars, truncatewords

from micawber import Cache, bootstrap_oembed

cache = Cache()  # Simple in-memory cache.
pr = bootstrap_oembed(cache=cache)

class Embed(models.Model):
    slug=models.CharField(max_length=500, verbose_name="slug")
    width=models.CharField(max_length=20, verbose_name="width", help_text="Only for link embeds(specify the width of embed code from ir's attributes)", blank=True,null=True, default=800)
    link=models.CharField(max_length=1500, verbose_name="Link Address of the Embed", help_text="example: https://youtube.com/something", blank=True,null=True)
    embed_code=models.TextField(max_length=10000, verbose_name="embed code", help_text="copy the embed code from your server and Past it here, if you use this field, the previous field will be ignored during template rendition", blank=True,null=True)
    description=models.TextField(max_length=10000, verbose_name="About this link/video", blank=True,null=True)
    
    def __str__(self): return self.slug
        
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('visitorsite:embed_viewing_url', args=[self.slug])

    @property
    def short_description(self):
        return truncatewords(self.description, 15)

    @property
    def short_embed_code(self):
        provider=self.embed_code.find("src")
        return self.embed_code[provider+13:150]

    @property
    def short_embed_link(self):
        try:
            provider=str(self.link).find("http")
            return self.link[provider+8:28]
        except:
            return None

visitorsite/models/pages.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Page(models.Model):
    title=models.CharField(verbose_name="Page Title", max_length=250)
    slug = models.SlugField(verbose_name=_('slug'), allow_unicode=True, max_length=255,
        help_text=_("The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/")
        )
    status = models.IntegerField(choices=((0,_("Draft")),(1,_("UnPublished")),(2,_("Published"))), default=2)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name=_('creator'),null=True,blank=True,
        editable=True,on_delete=models.SET_NULL,related_name='created_pages',limit_choices_to={'is_staff': True},
        )
    created_on = models.DateTimeField(verbose_name=_('Created On'),blank=True,null=True,db_index=True,editable=False,auto_now_add=True)
    updated_on = models.DateTimeField(verbose_name=_('Updated On'),auto_now= True)

    def __str__(self): return self.title
    
    def live(self):  
        if self.status == 2: 
            return True
    
    def get_template(self, request, *args, **kwargs):
        if request.is_ajax():
            return self.ajax_template or self.template
        else:
            return self.template

    class Meta:
        ordering = ['-created_on']

visitorsite/models/site_settings.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Settings(models.Model):
    status = models.IntegerField(choices=((0,_("Active")),(1,_("Need to be Reviewed")),(2,_("InActive"))), default=0, help_text="only one of the active settings will be applied(the one that has lower id)")
    image = models.ImageField(upload_to='images/site_settings/',verbose_name="Logo", blank=True, null=True)

    def __str__(self):
        return f'{self.id} - {self.status} - {self.image.url}'
        
    class Meta:
        managed = True
        verbose_name = 'Settings'
        verbose_name_plural = 'Settings'

comments/forms.py
from django import forms
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.utils.encoding import force_str
from django.utils.translation import pgettext_lazy, ngettext, gettext, gettext_lazy as _
from django.utils import timezone
from django_comments.forms import CommentSecurityForm
from .models import CComment

from . import get_model


COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)
DEFAULT_COMMENTS_TIMEOUT = getattr(settings, 'COMMENTS_TIMEOUT', (2 * 60 * 60))  # 2h


class CommentDetailsForm(CommentSecurityForm):
    """
    Handles the specific details of the comment (name, comment, etc.).
    """
    name = forms.CharField(label=pgettext_lazy("Person name", "Name"), max_length=50)
    # Translators: 'Comment' is a noun here.
    comment = forms.CharField(
        label=_('Comment'),
        widget=forms.Textarea(attrs={'class': "form-control h-100 w-100", 'rows': '1', 'cols': 'auto'}),
        max_length=COMMENT_MAX_LENGTH
    )

    def get_comment_object(self, site_id=None):
        """
        Return a new (unsaved) comment object based on the information in this
        form. Assumes that the form is already validated and will throw a
        ValueError if not.

        Does not set any of the fields that would come from a Request object
        (i.e. ``user`` or ``ip_address``).
        """
        if not self.is_valid():
            raise ValueError("get_comment_object may only be called on valid forms")

        CommentModel = self.get_comment_model()
        new = CommentModel(**self.get_comment_create_data(site_id=site_id))
        new = self.check_for_duplicate_comment(new)

        return new

    def get_comment_model(self):
        """
        Get the comment model to create with this form. Subclasses in custom
        comment apps should override this, get_comment_create_data, and perhaps
        check_for_duplicate_comment to provide custom comment models.
        """
        return get_model()

    def get_comment_create_data(self, site_id=None):
        """
        Returns the dict of data to be used to create a comment. Subclasses in
        custom comment apps that override get_comment_model can override this
        method to add extra fields onto a custom comment model.
        """
        return dict(
            content_type=ContentType.objects.get_for_model(self.target_object),
            object_pk=force_str(self.target_object._get_pk_val()),
            user_name=self.cleaned_data["name"],
            comment=self.cleaned_data["comment"],
            submit_date=timezone.now(),
            site_id=site_id or getattr(settings, "SITE_ID", None),
            is_public=True,
            is_removed=False,
        )

    def check_for_duplicate_comment(self, new):
        """
        Check that a submitted comment isn't a duplicate. This might be caused
        by someone posting a comment twice. If it is a dup, silently return the *previous* comment.
        """
        possible_duplicates = self.get_comment_model()._default_manager.using(
            self.target_object._state.db
        ).filter(
            content_type=new.content_type,
            object_pk=new.object_pk,
            user_name=new.user_name,
        )
        for old in possible_duplicates:
            if old.submit_date.date() == new.submit_date.date() and old.comment == new.comment:
                return old

        return new

    def clean_comment(self):
        """
        If COMMENTS_ALLOW_PROFANITIES is False, check that the comment doesn't
        contain anything in PROFANITIES_LIST.
        """
        comment = self.cleaned_data["comment"]
        if (not getattr(settings, 'COMMENTS_ALLOW_PROFANITIES', False) and
                getattr(settings, 'PROFANITIES_LIST', False)):
            bad_words = [w for w in settings.PROFANITIES_LIST if w in comment.lower()]
            if bad_words:
                raise forms.ValidationError(ngettext(
                    "Watch your mouth! The word %s is not allowed here.",
                    "Watch your mouth! The words %s are not allowed here.",
                    len(bad_words)) % get_text_list(
                    ['"%s%s%s"' % (i[0], '-' * (len(i) - 2), i[-1])
                     for i in bad_words], gettext('and')))
        return comment


class CCommentForm(CommentDetailsForm):
    honeypot = forms.CharField(required=False,
                               label=_('If you enter anything in this field '
                                       'your comment will be treated as spam'))

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value

    def get_comment_create_data(self, **kwargs):
        # Use the data of the superclass, and add in the title field
        data = super().get_comment_create_data(**kwargs)
        # data['title'] = self.cleaned_data['title']
        return data

visitorsite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models.posts import Post
from .models.embeds import Embed


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ()


class EmbedForm(forms.ModelForm):
    class Meta:
        model = Embed
        exclude = ()


class UserRegisterForm(UserCreationForm):
	honeypot = forms.CharField(required=False,label='If you enter anything in this field, your comment will be treated as spam')

	def clean_honeypot(self):
		"""Check that nothing's been entered into the honeypot."""
		value = self.cleaned_data["honeypot"]
		if value:
			raise forms.ValidationError("Oah, you're a bot..!")
		return value

	def save(self, commit=True):
		user = super(UserRegisterForm, self).save(commit=False)
		if commit:
			user.save()
		return user
	
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

visitorsite/views.py
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models.posts import Post, Topic
from .models.embeds import Embed
from .forms import PostForm, EmbedForm, UserRegisterForm


paginate_var = 9

class SignUp(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class TopicListing(ListView):
    queryset = Topic.objects.filter(status=2).order_by('-created_on')
    model = Topic 


class SpecificTopicPostsListing(ListView):
    queryset = Post.objects.filter(status=2).order_by('-created_on')
    model = Post
    paginate_by = paginate_var


class PostListing(ListView):
    queryset = Post.objects.filter(status=2).order_by('-created_on')
    model = Post 
    paginate_by = paginate_var


class VideoPostListing(ListView):
    queryset = Post.objects.filter(status=2, type=1).order_by('-created_on')
    model = Post 
    paginate_by = paginate_var


class NewsPostListing(ListView):
    queryset = Post.objects.filter(status=2, type=3).order_by('-created_on')
    model = Post 
    paginate_by = paginate_var


class ImagePostListing(ListView):
    queryset = Post.objects.filter(status=2, type=2).order_by('-created_on')
    model = Post 
    paginate_by = paginate_var


class PostDetailsViewing(DetailView):
    model = Post


class PostCreating(CreateView):
    model = Post 
    form_class = PostForm


class PostUpdating(UpdateView):
    model = Post
    form_class = PostForm


class PostDeleting(DeleteView):
    model = Post
    success_url = reverse_lazy('indexes_url')


#  -------------- Embeding -------------
class EmbedListing(ListView):
    queryset = Embed.objects.all()
    model = Embed 


class EmbedDetailsViewing(DetailView):
    model = Embed


class EmbedCreating(CreateView):
    model = Embed 
    form_class = EmbedForm


class EmbedUpdating(UpdateView):
    model = Embed
    form_class = EmbedForm


class EmbedDeleting(DeleteView):
    model = Embed
    success_url = reverse_lazy('Topices_url')

visitorsite/templates/indexes/indexes.html
{% extends "main.html" %}


{% block head %} 
    <title>My Posts</title>  
    
{% endblock head %}

{% block library_css %}
        .object.blog {box-shadow: 0 0 5px; margin: 16px; padding: 10px 32px;border-radius: 0 28px 28px; }
        .blog_list {display: block;}
{% endblock library_css %}

{% block content %}
    <h2 class="center">My Posts</h2>
    <div class="empty_line"></div>
    <div class="container">
        <div class="row blog_list">
            {% if object_list %}
                <ul class="list-group">
                    {% for topic in object_list %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ topic.get_absolute_url }}">
                                {{ topic.title }}
                            </a>
                            <span class="badge bg-primary rounded-pill">
                            {{ topic.posts.all|length }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="col-md-12">
                    <p>Oh, snap. Looks like we were too busy (serving the world) to build any Categories..!</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

visitorsite/templates/indexes/specific_posts.html
{% extends "main.html" %}
{% load comments %}
{% load static %}

{% block head %} 
    <title> This Topic's Posts</title> 
{% endblock head %}

{% block library_css %}
{% endblock library_css %}

{% block head-extra %}{% endblock head-extra %}

{% block body_class %}{% endblock body_class %}

{% block messages %}{% endblock messages %}

{% block header %}{% endblock header %}

{% block content %}
    <h2 class="center">My Topic's Posts</h2>
    <div class="empty_line"></div>
    <div class="container-fluid">
        <div class="grid  infinite-container" >
            {% if object_list %}
                <div class="grid are-images-unloaded">
                    <div class="grid__col_sizer"></div>
                    <div class="grid__gutter_sizer"></div>
                    {% for post in object_list %}
                        {% if post.get_topic_listing_slug in request.get_full_path  %}
                            <div class="grid__item ss-card bg-white shadow-sm rounded border">
                                <div class="hhcard">
                                    <div class="ss-card-header p-3 border-bottom">
                                        <span class="ss-author mr-3"><i class="far fa-caret-square-right"></i>{{post.creator}}</span>
                                        {% if post.date_published %}
                                            <span class="ss-published">{{ post.date_published }}</span>
                                        {% endif %}                                
                                    </div>
                                    {% if post.embed_file %}
                                        {% if post.embed_file.link %}
                                            {% load micawber_tags %}
                                            <div class="ratio ratio-16x9">
                                                {{ post.embed_file.link|oembed:"460x600" }}
                                            </div>
                                        {% else %}
                                            <div class="ratio ratio-16x9">
                                                {{ post.embed_file.embed_code|safe }}
                                            </div>
                                        {% endif %}
                                    {% elif post.image %}
                                        <img src="{{ post.image.url }}" width="100%" alt="{{ post.image.alt }}" class="header_image" />
                                    {% elif post.external_image %}
                                        <img src="{{post.external_image}}" width="100%" alt="{{ post.image.alt }}" class="header_image"
                                            style="-webkit-user-select: none;margin: auto;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;">
                                    {% endif %}
                                    <div class="card-content p-3">
                                        <div class="text-section mb-5">
                                            <h5 class="blog-list-title">
                                                <a href="{{ post.get_absolute_url }}" class="inner"><i><span class="fas fa-angle-double-right post-link-icon"></i></span>{{ post.title }}</a>
                                            </h5>
                                            {{ post.body|urlize|linebreaks|truncatewords:30 }}
                                        </div>
                                        <div class="ss-comment-section mb-4">
                                            <div class="comment mb-3">
                                                {% for comment in post.get_obj_latest_comments %}
                                                    {% if forloop.counter < 4 %}
                                                        <span class="username text-primary">
                                                            <p class="comment-byline text-uppercase mb-1 small">
                                                                <span class="small">#{{forloop.counter}}</span> <span class="username text-primary">{{comment.user_name }} - </span><span class="comment-datetime text-muted">{{comment.submit_date}}</span>
                                                            </p>
                                                        </span>                                                                                                   
                                                        <p class="comment-text">{{ comment.comment|urlize|linebreaks }}</p>
                                                    {% endif %}
                                                {% endfor %}
                                            </div>
                                        </div>
                                        {% if request.user.is_authenticated %}
                                            {% get_comment_form for post as form %}
                                                <form class="form-inline" action="{% comment_form_target %}?next=/" method="post">
                                                    {% csrf_token %}
                                                    <div id="results"></div> <!-- errors go here -->
                                                    {% for field in form %}
                                                        {% if field.name == "timestamp" or field.name == "security_hash" or field.name == "object_pk" or field.name == "content_type" %}
                                                            {{field}}
                                                        {% endif %}
                                                        {% if field.name == "name" %}
                                                        <input type="text" value="{{request.user}}" name="name" maxlength="50" style="display: none;"
                                                            id="id_name">
                                                        {% endif %}
                                                        {% if field.name == "email" %}
                                                        <input type="email" value="{{request.user.email}}" name="email" style="display: none;"
                                                            id="id_email">
                                                        {% endif %}
                                                        {% if field.name == "url" %}
                                                            <input type="url" value="{% if  " localhost" not in request.META.HTTP_HOST and "127.0.0.1" not in request.META.HTTP_HOST %}{{ request.META.HTTP_HOST }}{% endif %}" name="url"
                                                                style="display: none;" id="id_url">
                                                        {% endif %}
                                                        {% if field.name|lower == "comment" %}
                                                        <div class="d-flex">
                                                            <div class="flex-grow-1">

                                                                <label class="sr-only" for="add-reply">Add Reply</label>
                                                                <input type="text" name="comment" class="form-control w-100" id="id_comment"
                                                                    placeholder="">
                                                            </div>
                                                            <div class="ms-1"><button type="submit" name="submit" class="btn btn-primary btn-lg btn-reply"><i class="fas fa-reply"></i></button></div>
                                                        </div>
                                                        {% endif %}
                                                    {% endfor %}
                                                </form>
                                        {% else %}
                                            <p class="small"><a href="/accounts/login/?next=/{{ object.slug }}">Login</a> to comment.  <i class="far fa-comment"></i></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="col-md-12">
                    <p>Oh, snap. Looks like we were too busy (serving the world) to write any blog posts. Sorry.</p>
                </div>
            {% endif %}
        </div>
    </div>     
    <script src="{% static 'infinite-scroll.pkgd.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'masonry.pkgd.js' %}" crossorigin="anonymous"></script>
{% endblock %}

{% block extra_scripts %}
    // -- AJAX commenting --
    $('form').on('submit', function(event){
        event.preventDefault();
        // var $data = {{request.POST}};
        var $data = $(this).serialize();
        $.ajax({
            url : "/comments/post/", // the endpoint
            type : "POST", // http method
            data : $data , // data sent with the post request
            success : success_handler,
            error : errors_handler,
        });
    
        // handle a successful response
        function success_handler(json) {
            $('#post-text').val(''); // remove the value from the input
            alert("commented succesfully");
            $('form')[0].reset();
        };

        // handle a non-successful response
        function errors_handler(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        };
    });
    
    // --- masonry ---
    let grid = document.querySelector('.grid');

    let msnry = new Masonry( grid, {
        itemSelector: 'none', // select none at first
        columnWidth: '.grid__col_sizer',
        gutter: '.grid__gutter_sizer',
        percentPosition: true,
        is_paginated: false,
        stagger: 30,
        // nicer reveal transition
        visibleStyle: { transform: 'translateY(0)', opacity: 1 },
        hiddenStyle: { transform: 'translateY(100px)', opacity: 0 },
    });

    // initial items reveal
    imagesLoaded( grid, function() {
        grid.classList.remove('are-images-unloaded');
        msnry.options.itemSelector = '.grid__item';
        let items = grid.querySelectorAll('.grid__item');
        msnry.appended( items );
    });

    var nextSlugs = [{% if is_paginated %}{% for page in paginator %}{% if page.has_next %}"?page={{ page.next_page_number }}",{% endif %}{% endfor %}{% endif %}
    ];

    function getPath() {
        let slug = nextSlugs[ this.loadCount ];
        if ( slug ) {
            return `${slug}`;
        }
    }

    //--------------- init Infinte Scroll ----------------------//
    let infScroll = new InfiniteScroll( grid, {
        path: getPath,
        append: '.grid__item',
        outlayer: msnry,
        prefill: false,
        history: false,
        status: '.page-load-status',
    });
    $('.grid').toggleClass('are-images-unloaded');



{% endblock extra_scripts %}